services:
  postgres:
    image: pgvector/pgvector:0.8.0-pg17
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=maek_dev
      - POSTGRES_USER=maek
      - POSTGRES_PASSWORD=passwd
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U maek" ]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres-test:
    image: pgvector/pgvector:0.8.0-pg17
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=maek_test
      - POSTGRES_USER=maek
      - POSTGRES_PASSWORD=passwd
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U maek" ]
      interval: 5s
      timeout: 5s
      retries: 5

  ollama:
    image: ollama/ollama:0.5.12
    ports:
      - "11434:11434"
    restart: unless-stopped

volumes:
  pg_data:

