services:
  postgres:
    image: pgvector/pgvector:0.8.0-pg17
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=maek_dev
      - POSTGRES_USER=maek
      - POSTGRES_PASSWORD=passwd
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U maek"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres-test:
    image: pgvector/pgvector:0.8.0-pg17
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=maek_test
      - POSTGRES_USER=maek
      - POSTGRES_PASSWORD=passwd
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U maek"]
      interval: 5s
      timeout: 5s
      retries: 5

  y-sweet:
    image: ghcr.io/jamsocket/y-sweet:sha-db9709a
    ports:
      - "8081:8080"
    volumes:
      - ./tmp/ysweet_data:/data
    command: >
      y-sweet serve /data --host 0.0.0.0 --auth FriXYnx5Be4Me7jh+w64c0soR+ZIsQxc+7ZpswYF --url-prefix=http://localhost:8081/

volumes:
  pg_data: