// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: embeddings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

const getEmbeddingJobsByStatus = `-- name: GetEmbeddingJobsByStatus :many
SELECT id,
       note_id,
       workspace_id,
       content,
       status,
       attempts,
       created,
       updated
FROM embedding_job
WHERE status = $1
`

func (q *Queries) GetEmbeddingJobsByStatus(ctx context.Context, status pgtype.Int4) ([]EmbeddingJob, error) {
	rows, err := q.db.Query(ctx, getEmbeddingJobsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EmbeddingJob
	for rows.Next() {
		var i EmbeddingJob
		if err := rows.Scan(
			&i.ID,
			&i.NoteID,
			&i.WorkspaceID,
			&i.Content,
			&i.Status,
			&i.Attempts,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertEmbeddingJobs = `-- name: InsertEmbeddingJobs :one
INSERT INTO embedding_job (note_id, workspace_id, content)
VALUES ($1, $2, $3)
    RETURNING id
`

type InsertEmbeddingJobsParams struct {
	NoteID      int32
	WorkspaceID int32
	Content     string
}

func (q *Queries) InsertEmbeddingJobs(ctx context.Context, arg InsertEmbeddingJobsParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertEmbeddingJobs, arg.NoteID, arg.WorkspaceID, arg.Content)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertEmbeddings = `-- name: InsertEmbeddings :one
INSERT INTO embedding (note_id, workspace_id, chunk, embedding_vector)
VALUES ($1, $2, $3, $4)
    RETURNING id
`

type InsertEmbeddingsParams struct {
	NoteID          int32
	WorkspaceID     int32
	Chunk           pgtype.Text
	EmbeddingVector pgvector.Vector
}

func (q *Queries) InsertEmbeddings(ctx context.Context, arg InsertEmbeddingsParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertEmbeddings,
		arg.NoteID,
		arg.WorkspaceID,
		arg.Chunk,
		arg.EmbeddingVector,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const updateEmbeddingJobStatus = `-- name: UpdateEmbeddingJobStatus :exec
UPDATE embedding_job
SET status = $2
WHERE id = $1
`

type UpdateEmbeddingJobStatusParams struct {
	ID     int64
	Status pgtype.Int4
}

func (q *Queries) UpdateEmbeddingJobStatus(ctx context.Context, arg UpdateEmbeddingJobStatusParams) error {
	_, err := q.db.Exec(ctx, updateEmbeddingJobStatus, arg.ID, arg.Status)
	return err
}
