// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: tests.sql

package db

import (
	"context"
)

const truncateAllTables = `-- name: TruncateAllTables :exec
DO $$ DECLARE
    rec RECORD;
BEGIN
    -- Dynamically truncate all tables in the current schema which is the first value in search_path
    FOR rec IN (SELECT tablename FROM pg_tables WHERE schemaname = current_schema()) LOOP
        EXECUTE 'TRUNCATE TABLE ' || quote_ident(rec.tablename) || ' RESTART IDENTITY CASCADE';
    END LOOP;

END $$
`

func (q *Queries) TruncateAllTables(ctx context.Context) error {
	_, err := q.db.Exec(ctx, truncateAllTables)
	return err
}
