[settings]
experimental = true

[env]
CONFIG_FILE = '{{env.HOME}}/code/karngyan/maek/config/config.toml'
CGO_ENABLED = '0'
GOOSE_DRIVER = 'postgres'
GOOSE_DBSTRING = 'postgres://maek:passwd@localhost:5432/maek_dev?sslmode=disable'
GOOSE_MIGRATION_DIR = '{{env.HOME}}/code/karngyan/maek/db/migrations'

[tools]
go = '1.23.1'
node = '20.17.0'
'npm:npm' = '11.0.0'
'npm:pnpm' = '9.15.2'

'go:github.com/sqlc-dev/sqlc/cmd/sqlc' = '1.27.0'
'go:github.com/air-verse/air' = '1.61.5'
'go:github.com/pressly/goose/v3/cmd/goose' = '3.24.1'
