[settings]
experimental = true

[env]
CONFIG_FILE = '{{env.HOME}}/code/karngyan/maek/config/config.toml'
CGO_ENABLED = '0'

[tools]
go = '1.23.1'
atlas = '0.29.0'
node = '20.17.0'
'npm:npm' = '11.0.0'
'npm:pnpm' = '9.15.2'

'go:github.com/beego/bee/v2' = '2.3.0'
'go:github.com/sqlc-dev/sqlc/cmd/sqlc' = '1.27.0'
'go:github.com/stripe/pg-schema-diff/cmd/pg-schema-diff' = '0.8.0'
'go:github.com/air-verse/air' = '1.61.5'
